# Generated by Django 2.0.3 on 2018-07-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_profile_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('waitlist', models.BooleanField(default=False)),
                ('waitlist_date', models.DateTimeField(blank=True, null=True)),
                ('withdraw', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
            ],
        ),
    ]
