# Generated by Django 2.0.3 on 2018-07-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='level',
            field=models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('error', 'Problema'), ('success', 'Sucesso')], default='info', max_length=20),
        ),
    ]
