# Generated by Django 2.0.3 on 2018-07-13 04:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hacker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('NA', 'Prefiro não dizer')], max_length=2)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18, 'A idade mínima é 18 anos.')])),
                ('university', models.CharField(max_length=100)),
                ('enroll_year', models.IntegerField(null=True)),
                ('diet', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('special_needs', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shirt_size', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=3)),
                ('shirt_style', models.CharField(choices=[('Normal', 'Normal'), ('Babylook', 'Babylook')], max_length=15)),
                ('cv_type', models.CharField(blank=True, choices=[('LI', 'LinkedIn'), ('GH', 'GitHub'), ('WS', 'Website'), ('OT', 'Outro')], max_length=3, null=True)),
                ('cv', models.CharField(blank=True, max_length=300, null=True)),
                ('cv2_type', models.CharField(blank=True, choices=[('LI', 'LinkedIn'), ('GH', 'GitHub'), ('WS', 'Website'), ('OT', 'Outro')], max_length=3, null=True)),
                ('cv2', models.CharField(blank=True, max_length=300, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('essay', models.TextField(null=True)),
                ('hacker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hacker.Hacker')),
            ],
        ),
    ]
