# Generated by Django 2.0.3 on 2018-07-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='facebook',
        ),
    ]
