# Generated by Django 2.0.3 on 2018-07-23 20:58

import application.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_application_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='application',
            name='essay',
        ),
        migrations.RemoveField(
            model_name='application',
            name='shirt_size',
        ),
        migrations.RemoveField(
            model_name='application',
            name='shirt_style',
        ),
        migrations.RemoveField(
            model_name='application',
            name='special_needs',
        ),
        migrations.RemoveField(
            model_name='application',
            name='university',
        ),
        migrations.AddField(
            model_name='application',
            name='can_move',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='course',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cpf',
            field=models.CharField(default='', max_length=20, validators=[application.models.CPFValidator(0, 'CPF inválido')]),
        ),
        migrations.AddField(
            model_name='application',
            name='dream_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='education',
            field=models.CharField(choices=[('Ensino Fundamental', 'Ensino Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Graduação', 'Graduação'), ('Mestrado', 'Mestrado'), ('MBA', 'MBA'), ('Doutorado', 'Doutorado'), ('Pós Doutorado', 'Pós Doutorado')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='english_level',
            field=models.CharField(blank=True, choices=[('basic', 'Básico'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='excel_level',
            field=models.CharField(blank=True, choices=[('basic', 'Básico'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='extra_courses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='first_timer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interests',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='other_languages',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='referrer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='time_slots',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5, 'A idade mínima é 5 anos.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='enroll_year',
            field=models.IntegerField(null=True, verbose_name=[django.core.validators.MinValueValidator(1900, 'Hmm, como?'), django.core.validators.MaxValueValidator(2019), 'Hmm, como?']),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
