# Generated by Django 2.0.3 on 2018-07-23 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20180723_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='country',
            field=models.CharField(blank=True, choices=[['Brasil', 'Brasil'], ['USA', 'USA']], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(blank=True, choices=[['Engenharia Elétrica', 'Engenharia Elétrica'], ['Ciência da Computação', ' Ciência da Computação']], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='enroll_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900, 'Hmm, como?'), django.core.validators.MaxValueValidator(2019, 'Hmm, como?')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='school',
            field=models.CharField(blank=True, choices=[['Unicamp', 'Unicamp'], ['USP', 'USP']], max_length=100, null=True),
        ),
    ]
