# Generated by Django 2.0.3 on 2018-07-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20180724_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='education',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
