# Generated by Django 2.0.3 on 2018-08-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_settings_ticket_queue_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='verify_email',
            field=models.BooleanField(default=True),
        ),
    ]
