# Generated by Django 2.0.3 on 2018-07-26 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0009_auto_20180723_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('meta', 'Meta'), ('keynote', 'Keynote'), ('workshop', 'Workshop'), ('seminar', 'Palestra')], max_length=20)),
                ('start', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('require_register', models.BooleanField(default=False)),
                ('max_attendees', models.IntegerField()),
                ('attended', models.ManyToManyField(related_name='attended_events', to='user_profile.Profile')),
                ('attendees', models.ManyToManyField(related_name='selected_events', to='user_profile.Profile')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_events', to='user_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('comments', models.TextField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='user_profile.Profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='schedule.Event')),
            ],
        ),
    ]
