# Generated by Django 2.0.3 on 2018-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180731_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attended',
            field=models.ManyToManyField(related_name='attended_events', to='user_profile.Profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='selected_events', to='user_profile.Profile'),
        ),
    ]
