# Generated by Django 2.0.3 on 2018-07-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scan',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
