# Generated by Django 2.0.3 on 2018-07-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180717_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
