# Generated by Django 2.0.3 on 2018-08-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='checkedin',
            field=models.BooleanField(default=False),
        ),
    ]
