# Generated by Django 2.0.3 on 2018-07-11 21:29

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default=user_profile.models.gen_token, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(default=user_profile.models.gen_verification_code, max_length=20, unique=True),
        ),
    ]
