# Generated by Django 2.0.3 on 2018-07-12 17:13

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180711_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default=user_profile.models.gen_unique_id, max_length=20, unique=True),
        ),
    ]
