# Generated by Django 2.0.3 on 2018-07-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='_is_hacker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='_is_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='_is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
