# Generated by Django 2.0.3 on 2018-07-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20180723_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='_update_field',
        ),
        migrations.AddField(
            model_name='shortcuts',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
