# Generated by Django 2.0.3 on 2018-08-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20180723_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcuts',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
