# Generated by Django 2.0.3 on 2018-08-07 03:01

from django.db import migrations, models
import django.db.models.deletion
import helper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0010_shortcuts_is_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False)),
                ('skills', models.TextField(blank=True, default='')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(default=helper.models.calc_ticket_expires)),
                ('claimed', models.DateTimeField(default=None, null=True)),
                ('completed', models.DateTimeField(default=None, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_tickets', to='user_profile.Profile')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='user_profile.Profile')),
            ],
        ),
    ]
