# Generated by Django 2.0.3 on 2018-08-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='claimer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_tickets', to='user_profile.Profile'),
        ),
    ]
