# Generated by Django 2.0.3 on 2018-07-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('github', 'Github'), ('google', 'Google')], max_length=20)),
                ('social_id', models.CharField(max_length=50, unique=True)),
                ('access_token', models.TextField()),
                ('expires', models.IntegerField()),
                ('scopes', models.CharField(default='[]', max_length=2000)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_logins', to='user_profile.Profile')),
            ],
        ),
    ]
